### ISSUE TITLE
Diaspora share

### ISSUE THREAD

**Issue by Matthias84** [voc/media.ccc.de#7]
Hi, the CCC promotes decentralization and also maintains an [official diaspora account](https://pod.geraspora.de/people/40f71e3d974030bd). So I recommend to offer also an diaspora share option as https://sharetodiaspora.github.io

**Comment by manno** [comment]
I'd welcome any pull requests to implement this on the sharing tab.

**Comment by Matthias84** [comment]
@all here you go media.ccc.de/app/views/frontend/shared/_embedshare.haml

**Comment by jaywink** [comment]
https://share.diasporafoundation.org is the new officially hosted share endpoint, would recommend using that, for anyone doing a pull. There are multiple different options listed there for visualization.

**Comment by paskalito** [comment]
hi, i made this

https://github.com/paskalito/media.ccc.de/blob/patch-1/app/views/frontend/shared/_embedshare.haml

and this

https://github.com/paskalito/media.ccc.de/commit/01751918cf2337e3b170316921c2946687e823ad

by more or less reverse engeniering and guessing. since i have no idea about ruby etc.

but i think that should be all it needs. the thing i noticed that is missing is the icon. which seems to come from. fontawesome.

but unawesomely they do not have  a diaspora icon so that wont work.
http://fontawesome.io/icons/

apparently they are MIT dough so someone could/would have to please  do ^^ add a diaspora icon to that project. and then we could add necessary code to here:

https://github.com/voc/media.ccc.de/blob/master/vendor/assets/stylesheets/font-awesome.scss#L763

**Comment by paskalito** [comment]
hey just found an icon we can possibly use

https://github.com/diaspora/sharetodiaspora/blob/master/icons/diaspora-64.png

but i dont now how people here would like to have it integrated, and since i did not get feedback um just gonna pull my changes.

**Comment by manno** [comment]
Great! Thanks, we'll fix the icon later, somehow.

**Comment by paskalito** [comment]
hey thank you very much. for meging.


i tested it and found out that we get all the + in the title within the final post as well.
![bildschirmfoto vom 2016-01-03 11-22-57](https://cloud.githubusercontent.com/assets/8012793/12078295/7302a2c4-b20c-11e5-8edf-254e7b0c26dc.png)
i don't konw really what to do about it. i only found out the codes on the share diaspora site
https://share.diasporafoundation.org/about.html
use this snippet to generate the title.

    &title='+encodeURIComponent(document.title)
here we use

    title='.freeze + URI.encode_www_form_component(title)
(https://github.com/voc/media.ccc.de/blob/master/app/helpers/frontend/application_helper.rb#L26 )

i see this is diffrent syntax and i don't understand it. - but maybe someonw can make  a quick fix with that info.

otherwse just leave current state till then.
should i open a new issue for that?

**Comment by denschub** [comment]
JFTR, using the icon is perfectly fine for us. Feel free to ping me if you have any issues.
