### ISSUE TITLE
Event links to an IP

### ISSUE THREAD

**Issue by MaZderMind** [voc/media.ccc.de#70]
The Event "Chaosradio Documentation" links to an IP, not to media.ccc.de. This breaks the Certificate validation.
![screenshot from 2016-04-22 22-44-59](https://cloud.githubusercontent.com/assets/142237/14754789/e7f587ea-08dd-11e6-8326-36dfa51a21d5.png)

**Comment by manno** [comment]
This problem is fragment cache related. We do not enforce a fixed host name for the site. The nginx vhosts reacts to requests without a host name. If you manage to get into the cache other users will get your vhost instead of theirs.

4ad9934292af8a2a571feb16a87d6d75808da113 should fix that by using the path instead of the full url in a lot places.
Additionally we should change the nginx configuration to make it more strict.
